#!/bin/bash
#CUDA_VISIBLE_DEVICES=0 python 004_main.py --skip_wandb --use_batch_norm --exp_id test --run_id 002c --feats_type lsa --model_type minerva_detEx --feat_dim 32 --train_batch_size 512 --learning_rate 1e-3 --weight_decay 1e-2 --wd_ex 0.01 --p_factor 3 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --num_ex 128 --fix_ex --train_class_reps --train_ex_class
#CUDA_VISIBLE_DEVICES=0 python 003_main.py --exp_id 002 --run_id 003c --feats_type sen_trans --model_type minerva --feat_dim 32 --train_batch_size 512 --learning_rate 1e-3 --weight_decay 1e-2 --wd_ex 0.01 --p_factor 3 --do_feat 0.1 --do_class 0 --num_train_epochs 150 --use_g --num_ex 128 --fix_ex --train_class_reps --train_ex_class
#CUDA_VISIBLE_DEVICES=0 python 004_main.py --exp_id test --run_id 001 --feats_type sen_trans --model_type ffnn --class_dim 512 --num_train_epochs 3 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 1e-1 --do_class 0.5
#CUDA_VISIBLE_DEVICES=0 python 004_main.py --exp_id test --run_id 002 --feats_type sen_trans --model_type ffnn --class_dim 512 --num_train_epochs 3 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 1e-1 --do_class 0.5 --skip_wandb
#CUDA_VISIBLE_DEVICES=0 python 004_main.py --exp_id 001 --run_id 001 --skip_wandb --feats_type glove --model_type ffnn --class_dim 512 --num_train_epochs 150 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 1e-1 --do_class 0.6
#CUDA_VISIBLE_DEVICES=0 python 004_main.py --exp_id 001 --run_id 001d --skip_wandb --feats_type sen_trans --model_type minerva_detEx --feat_dim 32 --train_batch_size 512 --learning_rate 1e-3 --weight_decay 1e-2 --p_factor 3 --do_feat 0 --num_train_epochs 150 --use_g --num_ex 128 --fix_ex --model_name_or_path paraphrase-distilroberta-base-v2

CUDA_VISIBLE_DEVICES=0 python 004_main.py --exp_id 004 --run_id test --feats_type sen_trans --model_type minerva_detEx --p_factor 3 --num_ex 128 --fix_ex --skip_train
