#!/bin/bash

#CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id test --run_id test --feats_type sen_trans --model_type ffnn_init --auc_av weighted --class_dim 1024 --feat_dim 1024 --act0 ReLU --act1 ReLU --num_train_epochs 150 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 2 --do_class 0.8
#CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id test --run_id 001_m1 --feats_type sen_trans --model_type ffnn_init --minerva_initialisation minerva --auc_av weighted --class_dim 1024 --feat_dim 1024 --act0 ReLU --act1 ReLU --num_train_epochs 150 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 2 --do_class 0.8
#CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id test --run_id 001_m2 --feats_type sen_trans --model_type ffnn_init --minerva_initialisation minerva2 --auc_av weighted --class_dim 1024 --feat_dim 1024 --act0 ReLU --act1 ReLU --num_train_epochs 150 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 2 --do_class 0.8
#CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id test --run_id 001_m3 --feats_type sen_trans --model_type ffnn_init --minerva_initialisation minerva3 --auc_av weighted --class_dim 1024 --feat_dim 1024 --act0 ReLU --act1 ReLU --num_train_epochs 150 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 2 --do_class 0.8
#CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id test --run_id 001_m3 --feats_type sen_trans --model_type ffnn_init --minerva_initialisation minerva3 --train_alpha --auc_av weighted --class_dim 1024 --feat_dim 1024 --act0 ReLU --act1 ReLU --num_train_epochs 2 --lr_cr 1e-1 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 2 --do_class 0.8

#CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id test --run_id 001_m1 --feats_type sen_trans --model_type ffnn_init --minerva_initialisation minerva --auc_av weighted --feat_dim 1024 --act0 ReLU --act1 ReLU --num_train_epochs 150 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 2 --do_class 0.8
#CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id test --run_id 001_m2 --feats_type sen_trans --model_type ffnn_init --minerva_initialisation minerva2 --auc_av weighted --feat_dim 1024 --act0 ReLU --act1 ReLU --num_train_epochs 150 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 2 --do_class 0.8
#CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id test --run_id 001_m3 --feats_type sen_trans --model_type ffnn_init --minerva_initialisation minerva3 --auc_av weighted --feat_dim 1024 --act0 ReLU --act1 ReLU --num_train_epochs 150 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 2 --do_class 0.8


#CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id 010 --run_id 010 --feats_type lsa --model_type minerva_ffnn --auc_av weighted --p_factor 10 --num_ex 8192 --fix_ex --skip_train

CUDA_VISIBLE_DEVICES=0 python 001_is_main.py --exp_id 001 --run_id 001 --skip_wandb --num_train_epochs 10 --feats_type sen_trans --model_type ffnn_init --minerva_initialisation minerva4 --feat_dim 1024 --class_dim 1024 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 2 --do_class 0.8


#CUDA_VISIBLE_DEVICES=0 python 004_main.py --skip_wandb --use_batch_norm --exp_id test --run_id 002c --feats_type lsa --model_type minerva_detEx --feat_dim 32 --train_batch_size 512 --learning_rate 1e-3 --weight_decay 1e-2 --wd_ex 0.01 --p_factor 3 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --num_ex 128 --fix_ex --train_class_reps --train_ex_class
#CUDA_VISIBLE_DEVICES=0 python 003_main.py --exp_id 002 --run_id 003c --feats_type sen_trans --model_type minerva --feat_dim 32 --train_batch_size 512 --learning_rate 1e-3 --weight_decay 1e-2 --wd_ex 0.01 --p_factor 3 --do_feat 0.1 --do_class 0 --num_train_epochs 150 --use_g --num_ex 128 --fix_ex --train_class_reps --train_ex_class
#CUDA_VISIBLE_DEVICES=0 python 004_main.py --exp_id test --run_id 001 --feats_type sen_trans --model_type ffnn --class_dim 512 --num_train_epochs 3 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 1e-1 --do_class 0.5
#CUDA_VISIBLE_DEVICES=0 python 004_main.py --exp_id test --run_id 002 --feats_type sen_trans --model_type ffnn --class_dim 512 --num_train_epochs 3 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 1e-1 --do_class 0.5 --skip_wandb
#CUDA_VISIBLE_DEVICES=0 python 004_main.py --exp_id 001 --run_id 001 --skip_wandb --feats_type glove --model_type ffnn --class_dim 512 --num_train_epochs 150 --train_batch_size 512 --learning_rate 1e-4 --weight_decay 1e-1 --do_class 0.6
#CUDA_VISIBLE_DEVICES=0 python 004_main.py --exp_id 001 --run_id 001d --skip_wandb --feats_type sen_trans --model_type minerva_detEx --feat_dim 32 --train_batch_size 512 --learning_rate 1e-3 --weight_decay 1e-2 --p_factor 3 --do_feat 0 --num_train_epochs 150 --use_g --num_ex 128 --fix_ex --model_name_or_path paraphrase-distilroberta-base-v2

#CUDA_VISIBLE_DEVICES=0 python 006_main.py --exp_id 007 --run_id 001a --feats_type sen_trans --model_type minerva_detEx --feat_dim 32 --class_dim 2 --train_batch_size 512 --learning_rate 1e-4 --lr_cr 1e-4 --lr_ex 2 --weight_decay 1e-3 --wd_cr 1 --wd_ex 1e-3 --p_factor 0.25 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class --track_reps 5
#CUDA_VISIBLE_DEVICES=0 python 006_main.py --exp_id 007 --run_id 002a --feats_type sen_trans --model_type minerva_detEx --feat_dim 32 --class_dim 2 --train_batch_size 512 --learning_rate 1e-4 --lr_cr 1e-4 --lr_ex 2 --weight_decay 1e-3 --wd_cr 1 --wd_ex 1e-3 --p_factor 1 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class --track_reps 5
#CUDA_VISIBLE_DEVICES=0 python 006_main.py --exp_id 007 --run_id 003a --feats_type sen_trans --model_type minerva_detEx --feat_dim 32 --class_dim 2 --train_batch_size 512 --learning_rate 1e-4 --lr_cr 1e-1 --lr_ex 1e-1 --weight_decay 1e-3 --wd_cr 1 --wd_ex 1e-3 --p_factor 1 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class --track_reps 5
#CUDA_VISIBLE_DEVICES=0 python 006_main.py --exp_id 007 --run_id 004a --feats_type sen_trans --model_type minerva_detEx --feat_dim 32 --class_dim 2 --train_batch_size 512 --learning_rate 1e-4 --lr_cr 1e-1 --lr_ex 1e-1 --weight_decay 1e-3 --wd_cr 1e-1 --wd_ex 1e-1 --p_factor 1 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class --track_reps 5

#CUDA_VISIBLE_DEVICES=0 python 006_main.py --exp_id test --run_id 010 --skip_wandb --feats_type sen_trans --use_stratified_ex --model_type minerva_detEx --feat_dim 32 --class_dim 2 --train_batch_size 512 --learning_rate 1e-4 --lr_ex 1e-1 --weight_decay 1e-4 --wd_ex 1e-1 --p_factor 1 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class
#CUDA_VISIBLE_DEVICES=0 python 006_main.py --exp_id 008 --run_id 007 --skip_wandb --feats_type sen_trans --model_type minerva_detEx --feat_dim 32 --class_dim 2 --train_batch_size 512 --learning_rate 1e-4 --lr_ex 1e-1 --weight_decay 1e-2 --wd_ex 1e-1 --p_factor 1 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class
#CUDA_VISIBLE_DEVICES=0 python 006_main.py --exp_id 008 --run_id 008 --skip_wandb --feats_type sen_trans --model_type minerva_detEx --feat_dim 32 --class_dim 2 --train_batch_size 512 --learning_rate 1e-4 --lr_ex 1e-1 --weight_decay 1e-3 --wd_ex 1e-2 --p_factor 1 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class

#CUDA_VISIBLE_DEVICES=0 python 006_main.py --exp_id 010 --run_id test --feats_type sen_trans --model_type minerva_detEx --use_stratified_ex --feat_dim 32 --class_dim 4 --train_batch_size 512 --learning_rate 1e-4 --lr_ex 1e-2 --weight_decay 1e-5 --wd_ex 1e-5 --p_factor 2 --do_feat 0 --do_class 0 --num_train_epochs 300 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 001 --run_id test2 --skip_wandb --taxonomy ekman --feats_type sen_trans --model_type minerva_thresh --feat_dim 32 --class_dim 4 --train_batch_size 512 --learning_rate 1e-4 --lr_ex 1 --weight_decay 1e-3 --wd_ex 1e-3 --p_factor 2 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class --use_thresh
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 001 --run_id test2 --skip_wandb --use_mult --feats_type sen_trans --model_type minerva_thresh --feat_dim 32 --class_dim 4 --train_batch_size 512 --learning_rate 1e-4 --lr_ex 1 --weight_decay 1e-3 --wd_ex 1e-3 --p_factor 2 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class --use_thresh
#CUDA_VISIBLE_DEVICES=0 python 006_main.py --exp_id 010 --run_id test3 --feats_type sen_trans --model_type minerva_detEx --use_stratified_ex --feat_dim 32 --class_dim 4 --train_batch_size 512 --learning_rate 1e-4 --lr_ex 1 --weight_decay 1e-3 --wd_ex 1e-3 --p_factor 2 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 128 --fix_ex --model_name_or_path paraphrase-mpnet-base-v2 --train_class_reps --train_ex_class

#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 017 --run_id 033c2 --feats_type sen_trans --model_type minerva_thresh --use_thresh --use_mult --class_dim 2 --feat_dim 64 --train_batch_size 512 --learning_rate 1e-1 --lr_ex 1e-3 --lr_cr 1e-2 --weight_decay 1e-2 --wd_ex 1 --wd_cr 1e-2 --p_factor 9 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 4096 --fix_ex --train_ex_class --train_class_reps --track_reps 5
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 017 --run_id 033c2t --feats_type sen_trans --model_type minerva_thresh --use_thresh --class_dim 2 --feat_dim 64 --train_batch_size 512 --learning_rate 1e-1 --lr_ex 1e-3 --lr_cr 1e-2 --weight_decay 1e-2 --wd_ex 1 --wd_cr 1e-2 --p_factor 9 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 4096 --fix_ex --train_ex_class --train_class_reps --track_reps 5
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 017 --run_id 033c2m --feats_type sen_trans --model_type minerva_thresh --use_mult --class_dim 2 --feat_dim 64 --train_batch_size 512 --learning_rate 1e-1 --lr_ex 1e-3 --lr_cr 1e-2 --weight_decay 1e-2 --wd_ex 1 --wd_cr 1e-2 --p_factor 9 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 4096 --fix_ex --train_ex_class --train_class_reps --track_reps 5
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 017 --run_id 033c2n --feats_type sen_trans --skip_wandb --model_type minerva_thresh --class_dim 2 --feat_dim 64 --train_batch_size 512 --learning_rate 1e-1 --lr_ex 1e-3 --lr_cr 1e-2 --weight_decay 1e-2 --wd_ex 1 --wd_cr 1e-2 --p_factor 9 --do_feat 0 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 4096 --fix_ex --train_ex_class --train_class_reps --auc_av weighted

# Untrained Minerva LSA
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 001_ --feats_type lsa --model_type minerva_thresh --use_sm --p_factor 1 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 002_ --feats_type lsa --model_type minerva_thresh --use_sm --p_factor 5 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 003_ --feats_type lsa --model_type minerva_thresh --use_sm --p_factor 10 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 004_ --feats_type lsa --model_type minerva_thresh --use_sm --p_factor 20 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 005_ --feats_type lsa --model_type minerva_thresh --use_sm --p_factor 25 --num_ex 8192 --fix_ex --skip_train

# Untrained Minerva word2vec
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 001 --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 1 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 002 --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 5 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 003 --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 10 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 004 --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 20 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 005 --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 25 --num_ex 8192 --fix_ex --skip_train

#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 001_ --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 1 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 002_ --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 5 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 003_ --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 10 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 004_ --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 20 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 005_ --feats_type word2vec --model_type minerva_thresh --use_sm --p_factor 25 --num_ex 8192 --fix_ex --skip_train


# Untrained Minerva Roberta
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 001 --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 1 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 002 --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 5 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 003 --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 10 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 004 --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 20 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 007_main.py --exp_id 004 --run_id 005 --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 25 --num_ex 8192 --fix_ex --skip_train

#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 001_ --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 1 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 002_ --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 5 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 003_ --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 10 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 004_ --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 20 --num_ex 8192 --fix_ex --skip_train
#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 004 --run_id 005_ --feats_type sen_trans --model_type minerva_thresh --use_sm --p_factor 25 --num_ex 8192 --fix_ex --skip_train

#CUDA_VISIBLE_DEVICES=1 python 008_main.py --exp_id 004 --run_id 001 --feats_type lsa --model_type minerva_thresh --use_sm --p_factor 1 --num_ex 8192 --fix_ex --skip_train

#CUDA_VISIBLE_DEVICES=0 python 008_main.py --exp_id 001a --run_id 011 --skip_wandb --feats_type sen_trans --model_type minerva_thresh --auc_av weighted --use_thresh --use_mult --feat_dim 32 --train_batch_size 512 --learning_rate 1e-2 --weight_decay 1e-3 --p_factor 5 --do_feat 0.1 --do_class 0 --num_train_epochs 150 --use_g --use_sm --num_ex 8192 --fix_ex
