wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: huggingface
    huggingface_version: 4.11.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1683457933.144996
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.8.15
      5: 0.13.7
      6: 4.11.3
      8:
      - 5
